### ISSUE TITLE
`has()` method is not in NPM

### ISSUE THREAD

**Issue by MunGell** [yeoman/configstore#42] opened 2016-06-18 14:24 UTC
Hi there,

I just installed `configstore 2.0.0` from NPM and it does not have `has()` method.
I suspect new version was not published to npm yet?

**Comment by sindresorhus** [comment] 2016-06-18 15:48
Duplicate of https://github.com/yeoman/configstore/issues/41.

**Closed by sindresorhus** 2016-06-18 15:48 UTC

**Comment by MunGell** [comment] 2016-06-18 16:46
Hi @sindresorhus 

Sorry, haven't seen the duplicate.
Wouldn't it make sense to leave issues open until they are actually fixed?

**Comment by sindresorhus** [comment] 2016-06-18 17:23
No. There's no issue. Both of these issues are invalid. Readme in master reflects master. If you want the API for the version you're using, go to the relevant tag or the npm page.
